pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'node -v'
                sh 'npm -v'
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
    }
    tools {
        nodejs 'node18.18.0'
    }
}